(cua-mode)
(setq inhibit-startup-message t
      visible-bell t
      cursor-type 'bar)
(setq visible-bell t)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(global-display-line-numbers-mode 1)
(prefer-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(blink-cursor-mode 1)
(global-hl-line-mode +1)
(line-number-mode +1)
(global-display-line-numbers-mode 1)
(column-number-mode t)
(size-indication-mode t)
(global-auto-revert-mode t)
(setq-default tab-width 2
	      indent-tabs-mode nil)
(show-paren-mode t)
(setq dired-listing-switches "-l --group-directories-first")
(add-hook 'dired-mode-hook #'dired-hide-details-mode)
(require 'delsel)
(delete-selection-mode 1)
(load-theme 'monokai 't)
(setq backup-inhibited t)
(setq auto-save-default nil)
(global-set-key (kbd "C-+") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
